# Generated by Django 5.1.1 on 2024-10-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cash_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('amount', models.IntegerField()),
                ('cash_type', models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out')], default='NULL', max_length=10)),
                ('tran_type', models.CharField(choices=[('upi', 'UPI'), ('cash', 'Cash')], default='NULL', max_length=50)),
                ('tran_plat', models.CharField(choices=[('phonepe', 'PhonePe'), ('googlepay', 'Google Pay'), ('paytm', 'Paytm')], default='NULL', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='cash_in_entry',
        ),
    ]
